### PR TITLE
Initialize `rcd_2023_03_17` data

### LINKED ISSUE #109: New snapshot rcd_2023_03_17 after release 0.1.4

### PR DESCRIPTION
**Pull request by edelarua**
Closes #109

### CODE REVIEW

**Comment by shajoezhu** [comment]
any functions that we need to import from `lubridate`?

**Comment by Melkiades** [comment]
> @Melkiades any idea why it would require `lubridate` for loading cached data (only when `--as-cran`)? https://github.com/insightsengineering/scda.2022/actions/runs/4483374122/jobs/7882588517?pr=112#step:35:108

Could it be because of the metadata where there is the date and datetime class?

**Comment by edelarua** [comment]
> > @Melkiades any idea why it would require `lubridate` for loading cached data (only when `--as-cran`)? https://github.com/insightsengineering/scda.2022/actions/runs/4483374122/jobs/7882588517?pr=112#step:35:108
> 
> Could it be because of the metadata where there is the date and datetime class?

That shouldn't be the case since the date class uses `as.Date` and the datetime class uses `as.POSIXct`, both of which convert to base R classes.

**Review by Melkiades — APPROVED** [review]
Lgtm! I would just add something to NEWS ;) 

Well done!

**Pull request merged**
