### PR TITLE
update list of verdepcheck strategies

### PR DESCRIPTION
**Pull request by pawelru**

### CODE REVIEW

**Comment by pawelru** [comment]
This requires fixes in the `revdepcheck` testing logic. I am working on this.

**Comment by pawelru** [comment]
This should work after https://github.com/insightsengineering/verdepcheck/pull/43 got merged

**Comment by pawelru** [comment]
Ready for review.
Manual run of the pipeline succeed here: https://github.com/insightsengineering/scda.2022/actions/runs/9445454461

**Review by Melkiades — APPROVED** [review]
Lgtm!!!

**Pull request merged**
